#!/usr/bin/env bash
animal="dog"
case $animal in
    bird) echo "Avian";;
    dog|puppy) echo "Canine";;
    *) echo "No match!"
esac

echo -e

greet() {
    echo "Hi there, $1. Good $2"
}

echo "And now, a greeting..."
greet Landon Morning
greet Everybody Evening