#!/usr/bin/env bash

echo "While Loop"

declare -i a=0
while (( a <= 10 ))
do
    echo "a:$a"
    (( a++ ))
done

echo -e "\nUntil Loop"
declare -i b=0
until (( b > 5 )); do
    echo "b:$b"
    (( b++ ))
done